### ISSUE TITLE
HTML in tooltip?

### ISSUE THREAD

**Issue by phenomen** [Gibbu/svooltip#1]
I would like to use HTML formatted strings in the tooltip content but not sure how to do so.

If that's not possible yet, I would like to request it as an optional param e.g. `format: "raw" | "html"` that will internally use Svelte's `{@html ... }`

**Comment by Gibbu** [comment]
Since this directive is standalone function it cannot use `{@html}` but it can use `innerHTML` which is what I'm gonna use.
