### ISSUE TITLE
Do not show tooltip when `content` is `null`

### ISSUE THREAD

**Issue by FluffyDiscord** [Gibbu/svooltip#10]
There is no way in Svelte to optionally use the `use` direction. I would like to conditionally show/hide my tooltip, but currently there is no way to do that. The package leaves behind "arrow" element when `content` is `null`.

Would it be possible to either add new option to enable/disable the tooltip or simply don't show the tooltip when `content` is `null`?

![image](https://user-images.githubusercontent.com/10332247/224502495-5be3c372-8399-4575-abee-81082bd72fcf.png)

Tooltip "arrow" is left behind when `content` is `null`
![image](https://user-images.githubusercontent.com/10332247/224502499-c57887e0-b7ec-4ad6-b4e6-509a92335e33.png)

**Comment by Gibbu** [comment]
This should be fixed, update to `0.7.1` 👍

**Comment by FluffyDiscord** [comment]
Thank you, just a small typo in the new update, it's "visibility", not "visiblity"

**Comment by Gibbu** [comment]
Whoops. My bad. Fixed
