### ISSUE TITLE
smaller `arrow-size` values reveal the rotated box used to make the triangle

### ISSUE THREAD

**Issue by argyleink** [Gibbu/svooltip#11]
This size [from the docs](https://svooltip.vercel.app/#:~:text=origin%3A%20top%20right%3B%0A%7D-,css%20variables,-The%20default%20styling), does indeed make the arrow smaller, but also reveals the box used to make it:

```css
:root {
  --svooltip-arrow-size: 6px;
}
```

<img width="245" alt="Screenshot 2023-03-16 at 8 20 13 AM" src="https://user-images.githubusercontent.com/1134620/225664208-94c2cf71-171f-410d-ab6d-5a2bbe0dbf05.png">
<img width="387" alt="Screenshot 2023-03-16 at 8 20 39 AM" src="https://user-images.githubusercontent.com/1134620/225664212-f91d5bd9-11f1-41e7-a5be-f36aa38a6705.png">

**Comment by Gibbu** [comment]
I've made it dynamically calculate the arrow size so this should be fixed.
Update to `0.7.1`

**Comment by argyleink** [comment]
confirmed fixed 👍🏻 
appreesh the swiftness

happy st. patty's day!

**Comment by argyleink** [comment]
<img width="351" alt="Screenshot 2023-03-17 at 7 33 33 AM" src="https://user-images.githubusercontent.com/1134620/225934721-445f6690-3d63-45f8-b7d9-70af39f0a334.png">
<img width="249" alt="Screenshot 2023-03-17 at 7 33 36 AM" src="https://user-images.githubusercontent.com/1134620/225934724-06f7f26f-ea9f-47f5-9723-53efcdbab833.png">
