### ISSUE TITLE
No export conditions for svelte in package.json

### ISSUE THREAD

**Issue by JuxtNorth** [Gibbu/svooltip#19]
The package.json file of this library doesn't define any export condition for svelte, due to which this warning is shown.

```
[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
```

See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by Gibbu** [comment]
Fixed.
