### ISSUE TITLE
Tootltips stay forever

### ISSUE THREAD

**Issue by PlkMarudny** [Gibbu/svooltip#2]
Rapid pointer movement over a tooltipped element causes the tooltip to stay displayed forever. 

 The delay parameter only delays displaying the tooltip, but the event is always fired.

**Comment by Gibbu** [comment]
I can't seem to recreate this, can you send your action settings and what you're doing?

**Comment by PlkMarudny** [comment]
At this page, https://svooltip.vercel.app/ hover over the button labelled "Hover me for 1 second" quickly twice (i.e. do not wait 1 second, just move the mouse pointer over, out, over, out. The tooltip appears and does not want to go away.

**Comment by michapixel** [comment]
i'm having the same issue.
see this REPL

[https://svelte.dev/repl/1a8bf5eddbbc4749bae3a7475f2bf5a0?version=3.57.0](https://svelte.dev/repl/1a8bf5eddbbc4749bae3a7475f2bf5a0?version=3.57.0)

**Comment by michapixel** [comment]
i may add: we could use some sort of destroy function, whihc we could invoke in onDestroy events ...

**Comment by michapixel** [comment]
temp-fix:
put that in a onDestroy-method (you should set the selector to the one you're using. 
I'm using the body of my document, so i need to remove all svolltips, since there seems to be no way of knowing which one get's invoked by whom ... 
```
[...document.querySelectorAll('body > .svooltip')].forEach((el) => {el.remove()});
```
