### ISSUE TITLE
Request: Automatically add data-placement when auto-placement causes tooltip to move

### ISSUE THREAD

**Issue by saturnonearth** [Gibbu/svooltip#21]
I have some CSS classes as follows:

```css
.svooltip[data-placement^='top'] .svooltip-arrow {
	@apply border-b border-r;
}
.svooltip[data-placement^='bottom'] .svooltip-arrow {
	@apply border-t border-l;
}
```

But the issue is, they are not applied when the tooltip is overflowing and changes position, so I end up getting the incorrect classes for the position that it's in.

Example:

Correct placement:

![CleanShot 2024-02-02 at 16 03 51@2x](https://github.com/Gibbu/svooltip/assets/12503538/94178ef9-b812-4801-85e1-428e07cffd1b)

When it overflows:
![CleanShot 2024-02-02 at 16 04 27@2x](https://github.com/Gibbu/svooltip/assets/12503538/38e350a8-62a3-4aff-b002-fe5db18e21e7)

Notice the arrow border

**Comment by Gibbu** [comment]
Sorry for the omega late reply!
I've *finally* added this the newest updates.

Update to `svooltip@0.8.2` to get this working as indended.
