### ISSUE TITLE
Options is not exported?

### ISSUE THREAD

**Issue by howesteve** [Gibbu/svooltip#22]
Hello there. Thanks for this lib.

Any reason why `Props` is exported, but not `Options`? 

From `index.d.ts`

```ts
export { default as tooltip } from './tooltip.js';
export { default as Tooltip } from './Tooltip.svelte';
export type { Props } from './types';
export type { Placement } from '@floating-ui/dom';
```

**Comment by Gibbu** [comment]
Hey sorry for the omega late reply! 
I've *finally* exported both. No idea why I didn't do this in the first place.

Update to `svooltip@0.8.2` to get them!
