### ISSUE TITLE
feature request: update content after delay

### ISSUE THREAD

**Issue by ollema** [Gibbu/svooltip#3]
hi!

thanks for creating svooltip, I use it in nearly all of my svelte projects.

---

sometimes, I find that it would have been useful to different content in the tooltip depending on how long it has been hovered.

say that first you could display:
```
<username>
```
but after for example 1 seconds, the content would change to:
```
<username>
<status>
<bio>
<email>
```

I hope you get my idea, if not I would be happy to expand on this

**Comment by Gibbu** [comment]
I've added some lifecycle hooks that allows you to do this.
Example on the website: https://svooltip.vercel.app/#hook-functions

**Comment by ollema** [comment]
> I've added some lifecycle hooks that allows you to do this.
> Example on the website: https://svooltip.vercel.app/#hook-functions

great! this works like a charm!
