### ISSUE TITLE
Use Sass for basic styling

### ISSUE THREAD

**Issue by nika-d** [Gibbu/svooltip#4]
Dear @Gibbu , Thank you so much for this minimalistic tooltip, I love it! 😃

In our project, we use Sass and try to optimize the css output. Svooltip currently provides the basic styling only as css. Because of that, no matter how we @use oder @import the styles, we will always have some default values in our delivered css. For example the value `var(--svooltip-bg, #444)` will be delivered no matter what. 

We would like to avoid that. That´s why I would be glad to get the styles in Sass already. 

I think, it fits quite well to the minimalistic approach, because sass is already a dependency of the Svooltip project. So its just a little refactoring, not really adding anything new. 

I will implement that myself and make a pull request.

**Comment by Gibbu** [comment]
And chance we could still include the CSS vars like the original?

**Comment by Gibbu** [comment]
Something like:
```scss
$bg: var(--svooltip-bg, #444) !default;
```

That should still work, no?

**Comment by nika-d** [comment]
Hmm yes, could work maybe... I will try it out and write back later. For now, i convert the open pull request to Draft.

**Comment by nika-d** [comment]
Ok, now im really done. Thanks for the hint, how to implement it concisely!

**Comment by Gibbu** [comment]
Ahh, small issue. `svelte-package` doesn't seem to compile SCSS to CSS. So regular CSS users aren't anble to use the default styling.

**Comment by Gibbu** [comment]
I wrote a simple build script. Later today I'm going to setup actions to auto-build and publish.

**Comment by nika-d** [comment]
Thank you very much for your support! 😊
