### ISSUE TITLE
Unable to import default styling after updating to 0.4.2

### ISSUE THREAD

**Issue by ollema** [Gibbu/svooltip#6]
Hi!

After updating from 0.3.0 to 0.4.2 I am unable to import the default styling.

Both `import 'svooltip/styles.css';` and `import 'svooltip/svooltip.css';` gives me:
```
1:35:06 PM [vite] Internal server error: Missing "./styles.css" export in "svooltip" package
```

I am using a pretty standard svelte kit setup with tailwindcss and postcss enabled.

Let me know if I can provide more details.

```
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
    Memory: 24.23 GB / 31.33 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.11.0 - ~/.local/share/pnpm/node
    npm: 8.19.2 - ~/.local/share/pnpm/npm
  Browsers:
    Firefox: 107.0
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.104 => 1.0.0-next.104 
    @sveltejs/kit: 1.0.0-next.583 => 1.0.0-next.583 
    @tailwindcss/forms: ^0.5.3 => 0.5.3 
    @types/sharp: ^0.31.0 => 0.31.0 
    @typescript-eslint/eslint-plugin: ^5.46.0 => 5.46.0 
    @typescript-eslint/parser: ^5.46.0 => 5.46.0 
    autoprefixer: ^10.4.13 => 10.4.13 
    eslint: ^8.29.0 => 8.29.0 
    eslint-config-prettier: ^8.5.0 => 8.5.0 
    eslint-plugin-svelte3: ^4.0.0 => 4.0.0 
    postcss: ^8.4.20 => 8.4.20 
    prettier: ^2.8.1 => 2.8.1 
    prettier-plugin-svelte: ^2.9.0 => 2.9.0 
    sharp: ^0.31.2 => 0.31.2 
    svelte: ^3.54.0 => 3.54.0 
    svelte-check: ^2.10.2 => 2.10.2 
    svooltip: ^0.4.2 => 0.4.2 
    tailwindcss: ^3.2.4 => 3.2.4 
    tslib: ^2.4.1 => 2.4.1 
    typescript: ^4.9.4 => 4.9.4 
    vite: ^4.0.0 => 4.0.0

**Comment by Gibbu** [comment]
Ahhh I see what's going on.

`svelte-package` generates a `exports` object inside the generated `package.json` telling what to export for the package.
And since the `styles.css` doesn't exist at the time of the generation it doesn't get included.

`svelte-package` docs and typed comments don't really explain what `exports` and `files` do. So I'll just edit my `build.js` script to include `"./styles.css": "./styles.css"` to the generated `package.json`.

**Comment by ollema** [comment]
nice, this is working now!

however, I encountered another issue instead, will open a new issue
